// This file was generated by github.com/vektah/gqlgen, DO NOT EDIT

package graph

type BookInput struct {
	ID               *string  `json:"id"`
	Title            *string  `json:"title"`
	Authors          []string `json:"authors"`
	Url              *string  `json:"url"`
	Isbn             *string  `json:"isbn"`
	ImageUrlTemplate *string  `json:"imageUrlTemplate"`
}
