// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type BookInput struct {
	Title            *string  `json:"title"`
	Authors          []string `json:"authors"`
	URL              *string  `json:"url"`
	Isbn             *string  `json:"isbn"`
	ImageURLTemplate *string  `json:"imageUrlTemplate"`
}
